// Copyright (c) 2026 Hemashushu <hippospark@gmail.com>, All rights reserved.
//
// This Source Code Form is subject to the terms of
// the Mozilla Public License version 2.0 and additional exceptions.
// For more details, see the LICENSE, LICENSE.additional, and CONTRIBUTING files.

use ancpp::position::Position;

/// Represents a position in a file, including the file number and the position within that file.
/// This struct is used to track the location of the first token of a CST/AST node,
/// which is important for error reporting and debugging.
///
/// For example, the statement `return 1+2;` contains three tokens: `return`, `1`, and `2`.
/// The `FilePosition` of the return statement would point to the position of the `return` token,
/// and the `FilePosition` of the binary expression `1+2` would point to the position of the `1` token.
///
/// The file number and position can be obtained from the struct `TokenWithLocation`, which is
/// generated by the preprocessor.
#[derive(Debug, PartialEq, Clone, Copy, Default)]
pub struct FilePosition {
    pub file_number: usize,
    pub position: Position,
}

impl FilePosition {
    pub fn new(file_number: usize, position: &Position) -> Self {
        Self {
            file_number,
            position: *position,
        }
    }
}
